export const CountryWithLang: Record<string, string[]> = {
  MD: ["romanian"],
  US: ["english"],
  YT: ["french"],
  NR: ["english", "nauru"],
  MZ: ["portuguese"],
  BR: ["portuguese"],
  CV: ["portuguese"],
  GQ: ["french", "portuguese", "spanish"],
  AL: ["albanian"],
  VI: ["english"],
  NU: ["english", "niuean"],
  PW: ["english", "palauan"],
  NG: ["english"],
  VG: ["english"],
  GM: ["english"],
  SO: ["arabic", "somali"],
  YE: ["arabic"],
  MY: ["english", "malay"],
  DM: ["english"],
  GB: ["english"],
  MG: ["french", "malagasy"],
  EH: ["berber", "hassaniya", "spanish"],
  CY: ["greek", "turkish"],
  AG: ["english"],
  IE: ["english", "irish"],
  PY: ["guaraní", "spanish"],
  LK: ["sinhala", "tamil"],
  ZA: [
    "afrikaans",
    "english",
    "southern ndebele",
    "northern sotho",
    "southern sotho",
    "swazi",
    "tswana",
    "tsonga",
    "venda",
    "xhosa",
    "zulu",
  ],
  KW: ["arabic"],
  DZ: ["arabic"],
  HR: ["croatian"],
  MQ: ["french"],
  SL: ["english"],
  MP: ["carolinian", "chamorro", "english"],
  RW: ["english", "french", "kinyarwanda"],
  SY: ["arabic"],
  VC: ["english"],
  XK: ["albanian", "serbian"],
  LC: ["english"],
  HN: ["spanish"],
  JO: ["arabic"],
  TV: ["english", "tuvaluan"],
  NP: ["nepali"],
  LR: ["english"],
  HM: ["english"],
  AT: ["german"],
  GG: ["english", "french", "guernésiais"],
  CF: ["french", "sango"],
  MR: ["arabic"],
  DJ: ["arabic", "french"],
  FJ: ["english", "fijian", "fiji hindi"],
  NO: ["norwegian nynorsk", "norwegian bokmål", "sami"],
  LV: ["latvian"],
  FK: ["english"],
  KZ: ["kazakh", "russian"],
  AX: ["swedish"],
  TM: ["russian", "turkmen"],
  CC: ["english"],
  BG: ["bulgarian"],
  TK: ["english", "samoan", "tokelauan"],
  NC: ["french"],
  BB: ["english"],
  ST: ["portuguese"],
  AQ: [],
  BN: ["malay"],
  BT: ["dzongkha"],
  CM: ["english", "french"],
  AR: ["guaraní", "spanish"],
  AZ: ["azerbaijani"],
  MX: ["spanish"],
  MA: ["arabic", "berber"],
  GT: ["spanish"],
  KE: ["english", "swahili"],
  MT: ["english", "maltese"],
  CZ: ["czech", "slovak"],
  GI: ["english"],
  AW: ["dutch", "papiamento"],
  BL: ["french"],
  MC: ["french"],
  AE: ["arabic"],
  SS: ["english"],
  PR: ["english", "spanish"],
  SV: ["spanish"],
  FR: ["french"],
  NE: ["french"],
  CI: ["french"],
  GS: ["english"],
  BW: ["english", "tswana"],
  IO: ["english"],
  UZ: ["russian", "uzbek"],
  TN: ["arabic"],
  HK: ["english", "chinese"],
  MK: ["macedonian"],
  SR: ["dutch"],
  BE: ["german", "french", "dutch"],
  AS: ["english", "samoan"],
  SB: ["english"],
  UA: ["ukrainian"],
  FI: ["finnish", "swedish"],
  BF: ["french"],
  BA: ["bosnian", "croatian", "serbian"],
  IR: ["persian (farsi)"],
  CU: ["spanish"],
  ER: ["arabic", "english", "tigrinya"],
  SK: ["slovak"],
  LT: ["lithuanian"],
  MF: ["french"],
  PN: ["english"],
  GW: ["portuguese", "upper guinea creole"],
  MS: ["english"],
  TR: ["turkish"],
  PH: ["english", "filipino"],
  VU: ["bislama", "english", "french"],
  BO: ["aymara", "guaraní", "quechua", "spanish"],
  KN: ["english"],
  RO: ["romanian"],
  KH: ["khmer"],
  ZW: [
    "chibarwe",
    "english",
    "kalanga",
    "khoisan",
    "ndau",
    "northern ndebele",
    "chewa",
    "shona",
    "sotho",
    "tonga",
    "tswana",
    "tsonga",
    "venda",
    "xhosa",
    "zimbabwean sign language",
  ],
  JE: ["english", "french", "jèrriais"],
  KG: ["kyrgyz", "russian"],
  BQ: ["english", "dutch", "papiamento"],
  GY: ["english"],
  UM: ["english"],
  AM: ["armenian"],
  LB: ["arabic", "french"],
  ME: ["montenegrin"],
  GL: ["greenlandic"],
  PG: ["english", "hiri motu", "tok pisin"],
  ZM: ["english"],
  TT: ["english"],
  TF: ["french"],
  PE: ["aymara", "quechua", "spanish"],
  SE: ["swedish"],
  SD: ["arabic", "english"],
  PM: ["french"],
  OM: ["arabic"],
  IN: ["english", "hindi", "tamil"],
  TW: ["chinese"],
  MN: ["mongolian"],
  SN: ["french"],
  TZ: ["english", "swahili"],
  CA: ["english", "french"],
  CR: ["spanish"],
  CN: ["chinese"],
  CO: ["spanish"],
  MM: ["burmese"],
  RU: ["russian"],
  KP: ["korean"],
  KY: ["english"],
  BV: ["norwegian"],
  BY: ["belarusian", "russian"],
  PT: ["portuguese"],
  SZ: ["english", "swazi"],
  PL: ["polish"],
  CH: ["french", "swiss german", "italian", "romansh"],
  CG: ["french", "kikongo", "lingala"],
  VE: ["spanish"],
  PA: ["spanish"],
  NL: ["dutch"],
  WS: ["english", "samoan"],
  DK: ["danish"],
  LU: ["german", "french", "luxembourgish"],
  FO: ["danish", "faroese"],
  SI: ["slovene"],
  TG: ["french"],
  TH: ["thai"],
  WF: ["french"],
  BS: ["english"],
  TO: ["english", "tongan"],
  GR: ["greek"],
  SM: ["italian"],
  RE: ["french"],
  VA: ["italian", "latin"],
  BI: ["french", "kirundi"],
  BH: ["arabic"],
  MH: ["english", "marshallese"],
  TC: ["english"],
  IM: ["english", "manx"],
  HT: ["french", "haitian creole"],
  AF: ["dari", "pashto", "turkmen"],
  IL: ["arabic", "hebrew"],
  LY: ["arabic"],
  UY: ["spanish"],
  NF: ["english", "norfuk"],
  NI: ["spanish"],
  CK: ["english", "cook islands māori"],
  LA: ["lao"],
  CX: ["english"],
  SH: ["english"],
  AI: ["english"],
  FM: ["english"],
  DE: ["german"],
  GU: ["chamorro", "english", "spanish"],
  KI: ["english", "gilbertese"],
  SX: ["english", "french", "dutch"],
  ES: ["spanish", "catalan", "basque", "galician"],
  JM: ["english", "jamaican patois"],
  PS: ["arabic"],
  GF: ["french"],
  AD: ["catalan"],
  CL: ["spanish"],
  LS: ["english", "sotho"],
  AU: ["english"],
  GD: ["english"],
  GH: ["english"],
  SC: ["seychellois creole", "english", "french"],
  AO: ["portuguese"],
  BM: ["english"],
  PK: ["english", "urdu"],
  ML: ["french"],
  SA: ["arabic"],
  CW: ["english", "dutch", "papiamento"],
  KR: ["korean"],
  ET: ["amharic"],
  GP: ["french"],
  BD: ["bengali"],
  NZ: ["english", "māori", "new zealand sign language"],
  KM: ["arabic", "french", "comorian"],
  BZ: ["belizean creole", "english", "spanish"],
  UG: ["english", "swahili"],
  SG: ["english", "chinese", "malay", "tamil"],
  LI: ["german"],
  HU: ["hungarian"],
  IS: ["icelandic"],
  TJ: ["russian", "tajik"],
  NA: [
    "afrikaans",
    "german",
    "english",
    "herero",
    "khoekhoe",
    "kwangali",
    "lozi",
    "ndonga",
    "tswana",
  ],
  TL: ["portuguese", "tetum"],
  EG: ["arabic"],
  RS: ["serbian"],
  MU: ["english", "french", "mauritian creole"],
  MO: ["portuguese", "chinese"],
  PF: ["french"],
  MV: ["maldivian"],
  ID: ["indonesian"],
  CD: ["french", "kikongo", "lingala", "tshiluba", "swahili"],
  EE: ["estonian"],
  VN: ["vietnamese"],
  IT: ["italian"],
  GN: ["french"],
  TD: ["arabic", "french"],
  EC: ["spanish"],
  GE: ["georgian"],
  MW: ["english", "chewa"],
  IQ: ["arabic", "aramaic", "sorani"],
  SJ: ["norwegian"],
  BJ: ["french"],
  JP: ["japanese"],
  DO: ["spanish"],
  QA: ["arabic"],
  GA: ["french"],
};

export const PATHS = {
  english: "README.md",
  arabic: "ar-AR/README_AR.md",
  bosnian: "bs-BS/README-bs_BS.md",
  german: "de-DE/README.md",
  spanish: "es-ES/README-ES.md",
  french: "fr-FR/README_fr-FR.md",
  indonesian: "id-ID/README.md",
  italian: "it-IT/README.md",
  japanese: "ja-JA/README-ja_JA.md",
  korean: "ko-KR/README-ko_KR.md",
  dutch: "nl-NL/README.md",
  polish: "pl-PL/README.md",
  portuguese: "pt-BR/README_pt_BR.md",
  romanian: "ro-RO/README.ro.md",
  russian: "ru-RU/README.md",
  albanian: "sq-KS/README_sq_KS.md",
  thai: "th-TH/README.md",
  turkish: "tr-TR/README-tr_TR.md",
  ukrainian: "uk-UA/README.md",
  vietnamese: "vi-VI/README-vi.md",
  chinese: "zh-CN/README-zh_CN.md",
};

export const supportedLanguages = Object.keys(PATHS).slice(1);
export const fallbackLanguage = "english";
