import { Question } from "@/types";

export const CountryWithLang: Record<string, string[]> = {
  MD: ["romanian"],
  US: ["english"],
  YT: ["french"],
  NR: ["english", "nauru"],
  MZ: ["portuguese"],
  BR: ["portuguese"],
  CV: ["portuguese"],
  GQ: ["french", "portuguese", "spanish"],
  AL: ["albanian"],
  VI: ["english"],
  NU: ["english", "niuean"],
  PW: ["english", "palauan"],
  NG: ["english"],
  VG: ["english"],
  GM: ["english"],
  SO: ["arabic", "somali"],
  YE: ["arabic"],
  MY: ["english", "malay"],
  DM: ["english"],
  GB: ["english"],
  MG: ["french", "malagasy"],
  EH: ["berber", "hassaniya", "spanish"],
  CY: ["greek", "turkish"],
  AG: ["english"],
  IE: ["english", "irish"],
  PY: ["guaraní", "spanish"],
  LK: ["sinhala", "tamil"],
  ZA: [
    "afrikaans",
    "english",
    "southern ndebele",
    "northern sotho",
    "southern sotho",
    "swazi",
    "tswana",
    "tsonga",
    "venda",
    "xhosa",
    "zulu",
  ],
  KW: ["arabic"],
  DZ: ["arabic"],
  HR: ["croatian"],
  MQ: ["french"],
  SL: ["english"],
  MP: ["carolinian", "chamorro", "english"],
  RW: ["english", "french", "kinyarwanda"],
  SY: ["arabic"],
  VC: ["english"],
  XK: ["albanian", "serbian"],
  LC: ["english"],
  HN: ["spanish"],
  JO: ["arabic"],
  TV: ["english", "tuvaluan"],
  NP: ["nepali"],
  LR: ["english"],
  HM: ["english"],
  AT: ["german"],
  GG: ["english", "french", "guernésiais"],
  CF: ["french", "sango"],
  MR: ["arabic"],
  DJ: ["arabic", "french"],
  FJ: ["english", "fijian", "fiji hindi"],
  NO: ["norwegian nynorsk", "norwegian bokmål", "sami"],
  LV: ["latvian"],
  FK: ["english"],
  KZ: ["kazakh", "russian"],
  AX: ["swedish"],
  TM: ["russian", "turkmen"],
  CC: ["english"],
  BG: ["bulgarian"],
  TK: ["english", "samoan", "tokelauan"],
  NC: ["french"],
  BB: ["english"],
  ST: ["portuguese"],
  AQ: [],
  BN: ["malay"],
  BT: ["dzongkha"],
  CM: ["english", "french"],
  AR: ["guaraní", "spanish"],
  AZ: ["azerbaijani"],
  MX: ["spanish"],
  MA: ["arabic", "berber"],
  GT: ["spanish"],
  KE: ["english", "swahili"],
  MT: ["english", "maltese"],
  CZ: ["czech", "slovak"],
  GI: ["english"],
  AW: ["dutch", "papiamento"],
  BL: ["french"],
  MC: ["french"],
  AE: ["arabic"],
  SS: ["english"],
  PR: ["english", "spanish"],
  SV: ["spanish"],
  FR: ["french"],
  NE: ["french"],
  CI: ["french"],
  GS: ["english"],
  BW: ["english", "tswana"],
  IO: ["english"],
  UZ: ["russian", "uzbek"],
  TN: ["arabic"],
  HK: ["english", "chinese"],
  MK: ["macedonian"],
  SR: ["dutch"],
  BE: ["german", "french", "dutch"],
  AS: ["english", "samoan"],
  SB: ["english"],
  UA: ["ukrainian"],
  FI: ["finnish", "swedish"],
  BF: ["french"],
  BA: ["bosnian", "croatian", "serbian"],
  IR: ["persian (farsi)"],
  CU: ["spanish"],
  ER: ["arabic", "english", "tigrinya"],
  SK: ["slovak"],
  LT: ["lithuanian"],
  MF: ["french"],
  PN: ["english"],
  GW: ["portuguese", "upper guinea creole"],
  MS: ["english"],
  TR: ["turkish"],
  PH: ["english", "filipino"],
  VU: ["bislama", "english", "french"],
  BO: ["aymara", "guaraní", "quechua", "spanish"],
  KN: ["english"],
  RO: ["romanian"],
  KH: ["khmer"],
  ZW: [
    "chibarwe",
    "english",
    "kalanga",
    "khoisan",
    "ndau",
    "northern ndebele",
    "chewa",
    "shona",
    "sotho",
    "tonga",
    "tswana",
    "tsonga",
    "venda",
    "xhosa",
    "zimbabwean sign language",
  ],
  JE: ["english", "french", "jèrriais"],
  KG: ["kyrgyz", "russian"],
  BQ: ["english", "dutch", "papiamento"],
  GY: ["english"],
  UM: ["english"],
  AM: ["armenian"],
  LB: ["arabic", "french"],
  ME: ["montenegrin"],
  GL: ["greenlandic"],
  PG: ["english", "hiri motu", "tok pisin"],
  ZM: ["english"],
  TT: ["english"],
  TF: ["french"],
  PE: ["aymara", "quechua", "spanish"],
  SE: ["swedish"],
  SD: ["arabic", "english"],
  PM: ["french"],
  OM: ["arabic"],
  IN: ["english", "hindi", "tamil"],
  TW: ["chinese"],
  MN: ["mongolian"],
  SN: ["french"],
  TZ: ["english", "swahili"],
  CA: ["english", "french"],
  CR: ["spanish"],
  CN: ["chinese"],
  CO: ["spanish"],
  MM: ["burmese"],
  RU: ["russian"],
  KP: ["korean"],
  KY: ["english"],
  BV: ["norwegian"],
  BY: ["belarusian", "russian"],
  PT: ["portuguese"],
  SZ: ["english", "swazi"],
  PL: ["polish"],
  CH: ["french", "swiss german", "italian", "romansh"],
  CG: ["french", "kikongo", "lingala"],
  VE: ["spanish"],
  PA: ["spanish"],
  NL: ["dutch"],
  WS: ["english", "samoan"],
  DK: ["danish"],
  LU: ["german", "french", "luxembourgish"],
  FO: ["danish", "faroese"],
  SI: ["slovene"],
  TG: ["french"],
  TH: ["thai"],
  WF: ["french"],
  BS: ["english"],
  TO: ["english", "tongan"],
  GR: ["greek"],
  SM: ["italian"],
  RE: ["french"],
  VA: ["italian", "latin"],
  BI: ["french", "kirundi"],
  BH: ["arabic"],
  MH: ["english", "marshallese"],
  TC: ["english"],
  IM: ["english", "manx"],
  HT: ["french", "haitian creole"],
  AF: ["dari", "pashto", "turkmen"],
  IL: ["arabic", "hebrew"],
  LY: ["arabic"],
  UY: ["spanish"],
  NF: ["english", "norfuk"],
  NI: ["spanish"],
  CK: ["english", "cook islands māori"],
  LA: ["lao"],
  CX: ["english"],
  SH: ["english"],
  AI: ["english"],
  FM: ["english"],
  DE: ["german"],
  GU: ["chamorro", "english", "spanish"],
  KI: ["english", "gilbertese"],
  SX: ["english", "french", "dutch"],
  ES: ["spanish", "catalan", "basque", "galician"],
  JM: ["english", "jamaican patois"],
  PS: ["arabic"],
  GF: ["french"],
  AD: ["catalan"],
  CL: ["spanish"],
  LS: ["english", "sotho"],
  AU: ["english"],
  GD: ["english"],
  GH: ["english"],
  SC: ["seychellois creole", "english", "french"],
  AO: ["portuguese"],
  BM: ["english"],
  PK: ["english", "urdu"],
  ML: ["french"],
  SA: ["arabic"],
  CW: ["english", "dutch", "papiamento"],
  KR: ["korean"],
  ET: ["amharic"],
  GP: ["french"],
  BD: ["bengali"],
  NZ: ["english", "māori", "new zealand sign language"],
  KM: ["arabic", "french", "comorian"],
  BZ: ["belizean creole", "english", "spanish"],
  UG: ["english", "swahili"],
  SG: ["english", "chinese", "malay", "tamil"],
  LI: ["german"],
  HU: ["hungarian"],
  IS: ["icelandic"],
  TJ: ["russian", "tajik"],
  NA: [
    "afrikaans",
    "german",
    "english",
    "herero",
    "khoekhoe",
    "kwangali",
    "lozi",
    "ndonga",
    "tswana",
  ],
  TL: ["portuguese", "tetum"],
  EG: ["arabic"],
  RS: ["serbian"],
  MU: ["english", "french", "mauritian creole"],
  MO: ["portuguese", "chinese"],
  PF: ["french"],
  MV: ["maldivian"],
  ID: ["indonesian"],
  CD: ["french", "kikongo", "lingala", "tshiluba", "swahili"],
  EE: ["estonian"],
  VN: ["vietnamese"],
  IT: ["italian"],
  GN: ["french"],
  TD: ["arabic", "french"],
  EC: ["spanish"],
  GE: ["georgian"],
  MW: ["english", "chewa"],
  IQ: ["arabic", "aramaic", "sorani"],
  SJ: ["norwegian"],
  BJ: ["french"],
  JP: ["japanese"],
  DO: ["spanish"],
  QA: ["arabic"],
  GA: ["french"],
};

export const successSound = "/assets/success.wav";
export const levelUpSound = "/assets/level-up.mp3";
export const errorSound = "/assets/wrong.mp3";
export const LOCAL_STORAGE_KEY = "learn-javascript";

export const PATHS: Record<string, string> = {
  english: "README.md",
  // arabic: "ar-AR/README_AR.md", // not working
  // bosnian: "bs-BS/README-bs_BS.md", //not working
  german: "de-DE/README.md",
  spanish: "es-ES/README-ES.md",
  french: "fr-FR/README_fr-FR.md",
  indonesian: "id-ID/README.md",
  italian: "it-IT/README.md",
  japanese: "ja-JA/README-ja_JA.md",
  korean: "ko-KR/README-ko_KR.md",
  dutch: "nl-NL/README.md",
  polish: "pl-PL/README.md",
  portuguese: "pt-BR/README_pt_BR.md",
  romanian: "ro-RO/README.ro.md",
  russian: "ru-RU/README.md",
  albanian: "sq-KS/README_sq_KS.md",
  thai: "th-TH/README.md",
  turkish: "tr-TR/README-tr_TR.md",
  ukrainian: "uk-UA/README.md",
  vietnamese: "vi-VI/README-vi.md",
  chinese: "zh-CN/README-zh_CN.md", //not working
};

export const supportedLanguages = Object.keys(PATHS);
export const fallbackLanguage = "english";

export const testQuestions: Question[] = [
  {
    id: "1uwet9",
    question: "What's the output?",
    options: [
      { value: "A", text: "`0 1 2` and `0 1 2`" },
      { value: "B", text: "`0 1 2` and `3 3 3`" },
      { value: "C", text: "`3 3 3` and `0 1 2`" },
    ],
    answer: "C",
    explanation:
      "Because of the event queue in JavaScript, the `setTimeout` callback function is called _after_ the loop has been executed. Since the variable `i` in the first loop was declared using the `var` keyword, this value was global. During the loop, we incremented the value of `i` by `1` each time, using the unary operator `++`. By the time the `setTimeout` callback function was invoked, `i` was equal to `3` in the first example.In the second loop, the variable `i` was declared using the `let` keyword: variables declared with the `let` (and `const`) keyword are block-scoped (a block is anything between `{ }`). During each iteration, `i` will have a new value, and each value is scoped inside the loop.",
    code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}\n\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}\n",
  },
  {
    id: "G0AOWb",
    question: "What's the output?",
    options: [
      { value: "A", text: "`20` and `62.83185307179586`" },
      { value: "B", text: "`20` and `NaN`" },
      { value: "C", text: "`20` and `63`" },
      { value: "D", text: "`NaN` and `63`" },
    ],
    answer: "B",
    explanation:
      "Note that the value of `diameter` is a regular function, whereas the value of `perimeter` is an arrow function.With arrow functions, the `this` keyword refers to its current surrounding scope, unlike regular functions! This means that when we call `perimeter`, it doesn't refer to the shape object, but to its surrounding scope (window for example).Since there is no value `radius` in the scope of the arrow function, `this.radius` returns `undefined` which, when multiplied by `2 * Math.PI`, results in `NaN`.",
    code: "const shape = {\n  radius: 10,\n  diameter() {\n    return this.radius * 2;\n  },\n  perimeter: () => 2 * Math.PI * this.radius,\n};\n\nconsole.log(shape.diameter());\nconsole.log(shape.perimeter());\n",
  },
  {
    id: "nOSfZk",
    question: "What's the output?",
    options: [
      { value: "A", text: "`1` and `false`" },
      { value: "B", text: "`false` and `NaN`" },
      { value: "C", text: "`false` and `false`" },
    ],
    answer: "A",
    explanation:
      "The unary plus tries to convert an operand to a number. `true` is `1`, and `false` is `0`.The string `'Lydia'` is a truthy value. What we're actually asking, is \"Is this truthy value falsy?\". This returns `false`.",
    code: "+true;\n!'Lydia';\n",
  },
  {
    id: "vhY2Ip",
    question: "Which one is true?",
    options: [
      { value: "A", text: "`mouse.bird.size` is not valid" },
      { value: "B", text: "`mouse[bird.size]` is not valid" },
      { value: "C", text: '`mouse[bird["size"]]` is not valid' },
      { value: "D", text: "All of them are valid" },
    ],
    answer: "A",
    explanation:
      'In JavaScript, all object keys are strings (unless it\'s a Symbol). Even though we might not _type_ them as strings, they are always converted into strings under the hood.JavaScript interprets (or unboxes) statements. When we use bracket notation, it sees the first opening bracket `[` and keeps going until it finds the closing bracket `]`. Only then, it will evaluate the statement.`mouse[bird.size]`: First it evaluates `bird.size`, which is `"small"`. `mouse["small"]` returns `true`However, with dot notation, this doesn\'t happen. `mouse` does not have a key called `bird`, which means that `mouse.bird` is `undefined`. Then, we ask for the `size` using dot notation: `mouse.bird.size`. Since `mouse.bird` is `undefined`, we\'re actually asking `undefined.size`. This isn\'t valid, and will throw an error similar to `Cannot read property "size" of undefined`.',
    code: "const bird = {\n  size: 'small',\n};\n\nconst mouse = {\n  name: 'Mickey',\n  small: true,\n};\n",
  },
  {
    id: "PjJTk1",
    question: "What's the output?",
    options: [
      { value: "A", text: "`Hello`" },
      { value: "B", text: "`Hey!`" },
      { value: "C", text: "`undefined`" },
      { value: "D", text: "`ReferenceError`" },
      { value: "E", text: "`TypeError`" },
    ],
    answer: "A",
    explanation:
      'In JavaScript, all objects interact by _reference_ when setting them equal to each other.First, variable `c` holds a value to an object. Later, we assign `d` with the same reference that `c` has to the object.<img src="https://i.imgur.com/ko5k0fs.png" width="200">When you change one object, you change all of them.',
    code: "let c = { greeting: 'Hey!' };\nlet d;\n\nd = c;\nc.greeting = 'Hello';\nconsole.log(d.greeting);\n",
  },
  {
    id: "FvVcRH",
    question: "What's the output?",
    options: [
      { value: "A", text: "`true` `false` `true`" },
      { value: "B", text: "`false` `false` `true`" },
      { value: "C", text: "`true` `false` `false`" },
      { value: "D", text: "`false` `true` `true`" },
    ],
    answer: "C",
    explanation:
      "`new Number()` is a built-in function constructor. Although it looks like a number, it's not really a number: it has a bunch of extra features and is an object.When we use the `==` operator (Equality operator), it only checks whether it has the same _value_. They both have the value of `3`, so it returns `true`.However, when we use the `===` operator (Strict equality operator), both value _and_ type should be the same. It's not: `new Number()` is not a number, it's an **object**. Both return `false.`",
    code: "let a = 3;\nlet b = new Number(3);\nlet c = 3;\n\nconsole.log(a == b);\nconsole.log(a === b);\nconsole.log(b === c);\n",
  },
  {
    id: "U2tjOs",
    question: "What's the output?",
    options: [
      { value: "A", text: "`orange`" },
      { value: "B", text: "`purple`" },
      { value: "C", text: "`green`" },
      { value: "D", text: "`TypeError`" },
    ],
    answer: "D",
    explanation:
      "The `colorChange` function is static. Static methods are designed to live only on the constructor in which they are created, and cannot be passed down to any children or called upon class instances. Since `freddie` is an instance of class Chameleon, the function cannot be called upon it. A `TypeError` is thrown.",
    code: "class Chameleon {\n  static colorChange(newColor) {\n    this.newColor = newColor;\n    return this.newColor;\n  }\n\n  constructor({ newColor = 'green' } = {}) {\n    this.newColor = newColor;\n  }\n}\n\nconst freddie = new Chameleon({ newColor: 'purple' });\nconsole.log(freddie.colorChange('orange'));\n",
  },
  {
    id: "D786wK",
    question: "What's the output?",
    options: [
      { value: "A", text: "`{}`" },
      { value: "B", text: "`ReferenceError" },
      { value: "C", text: "`undefined`" },
    ],
    answer: "A",
    explanation:
      'It logs the object, because we just created an empty object on the global object! When we mistyped `greeting` as `greetign`, the JS interpreter actually saw this as:1. `global.greetign = {}` in Node.js\n2. `window.greetign = {}`, `frames.greetign = {}` and `self.greetign` in browsers.\n3. `self.greetign` in web workers.\n4. `globalThis.greetign` in all environments.In order to avoid this, we can use `"use strict"`. This makes sure that you have declared a variable before setting it equal to anything.',
    code: "let greeting;\ngreetign = {}; // Typo!\nconsole.log(greetign);\n",
  },
  {
    id: "LizbJ6",
    question: "What happens when we do this?",
    options: [
      { value: "A", text: "Nothing, this is totally fine!" },
      {
        value: "B",
        text: "`SyntaxError`. You cannot add properties to a function this way.",
      },
      { value: "C", text: '`"Woof"` gets logged.' },
      { value: "D", text: "`ReferenceError`" },
    ],
    answer: "A",
    explanation:
      "This is possible in JavaScript, because functions are objects! (Everything besides primitive types are objects)A function is a special type of object. The code you write yourself isn't the actual function. The function is an object with properties. This property is invocable.",
    code: "function bark() {\n  console.log('Woof!');\n}\n\nbark.animal = 'dog';\n",
  },
];
